### ISSUE TITLE
Another task

### ISSUE THREAD

**Issue by PodstDO** [AlexYalovoy/ArrayRealisation#25]
This method make one more mistake in instance tests. And this method is from another task.

https://github.com/AlexYalovoy/ArrayRealisation/blob/966260967d886a732b62edf6a87ca69ca3e92fec/src/index.js#L219-L230

**Comment by AlexYalovoy** [comment]
I don't agree with you.
There isn't information about where we have to do toPrimirtive implementation.
It works good.
+
I have fixed instance test  and i'v told Timophey about that.

All is fine and this isn't a error/mistake.

**Comment by motifej** [comment]
sometimes the initiative is punishable) and this is the case! I see no reason not to include this method in the implementation! Sasha, good job) BUT! this implementation is not correct! you have to use same logic as toString method
