### ISSUE TITLE
Edit the check

### ISSUE THREAD

**Issue by PodstDO** [AlexYalovoy/ArrayRealisation#29]
`(this.length === 0 && initValue)` -- it's more clearly.

https://github.com/AlexYalovoy/ArrayRealisation/blob/966260967d886a732b62edf6a87ca69ca3e92fec/src/index.js#L68

**Comment by AlexYalovoy** [comment]
In this if-statement I check for case like:
array is empty but we have passed initValue to reduce
But in your variant 

> this.length === 0 && initValue

if we pass any 'falseble' value as initValue (like '' , 0, null) check fails.
That's why I explicit check for undefined.

My variant is correct.
