### ISSUE TITLE
Remove unused variable

### ISSUE THREAD

**Issue by PodstDO** [AlexYalovoy/ArrayRealisation#34]
You should remove this ternary operator and `context `variable.

https://github.com/AlexYalovoy/ArrayRealisation/blob/966260967d886a732b62edf6a87ca69ca3e92fec/src/index.js#L176

Use `thisArg` instead of `context`.

https://github.com/AlexYalovoy/ArrayRealisation/blob/966260967d886a732b62edf6a87ca69ca3e92fec/src/index.js#L179

**Comment by motifej** [comment]
i am not agree,  but i guess we can use ES6 and code below
```function(cb, thisArg = this) {```

**Comment by AlexYalovoy** [comment]
He is right. If thisArg is not passed cb is called with undefined context and not with this.

Mdn (https://tinyurl.com/o4xk6br):
If a thisArg parameter is provided to find, it will be used as the this for each invocation of the callback. If it is not provided, then undefined is used.
