### ISSUE TITLE
Why do You use Math.abs()?

### ISSUE THREAD

**Issue by PodstDO** [AlexYalovoy/ArrayRealisation#36]
For what do You use  `Math.abs(beginArg)`? This option also passed tests ` if (beginArg < 0 && beginArg < this.length)`.

https://github.com/AlexYalovoy/ArrayRealisation/blob/966260967d886a732b62edf6a87ca69ca3e92fec/src/index.js#L200

**Comment by AlexYalovoy** [comment]
If beginArg less than 0 it always is less than this.length or i'm not right?
Example:
beginArg = -1
this.length can be [0; infinity]

`beginArg < this.length`  - this check is worthless

maybe I may replace `Math.abs(beginArg) < this.length` with 
`beginArg > -this.length`

But initial variant still better than suggested one.
